sudo: required
services:
  - docker

before_install:
  - docker build -t azeemz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true azeemz/react-test npm run test

after_success:
  - docker build -t azeemz/multi-client ./client
  - docker build -t azeemz/multi-nginx ./nginx
  - docker build -t azeemz/multi-server ./server
  - docker build -t azeemz/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push azeemz/multi-client
  - docker push azeemz/multi-nginx
  - docker push azeemz/multi-server
  - docker push azeemz/multi-worker